security:
    encoders:
        "Api\Bundle\UserBundle\Entity\User":
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        main:
            pattern: ^/
            fos_oauth: true
            stateless: true
            anonymous: true
    access_control:
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
    acl:
        connection: default